### ISSUE TITLE
Tanks demo broken

### ISSUE THREAD

**Issue by brunis** [WebAssembly/website#87] opened 2017-03-13 09:23 UTC
I run out of memory (firefox and chrome), but i'm assuming this is a Unity WebGL playback issue?

**Comment by kripken** [comment] 2017-03-13 21:31
Hmm, it should not take that much memory - how much memory does your system have, and how much does it use before running out?

**Comment by hun-nemethpeter** [comment] 2017-03-25 20:48
I have the same problem. It used to work some days ago but now it just say:

"The browser could not allocate enough memory for the WebGL content. If you are the developer of this content, try allocating less memory to your WebGL build in the WebGL player settings."

I have system 16GB RAM and only chrome is opened with that tab.

**Comment by IntrepidPig** [comment] 2017-08-13 19:21
I have this issue on Arch Linux with 8gb of ram on Firefox and Google Chrome. Chrome got the music to play for about a second, but both instantly gave an out of memory error.

**Comment by hun-nemethpeter** [comment] 2017-12-30 03:09
Still not working, here is the console output:

Invoking error handler due to
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 50331648, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (tanks.wasm.framework.unityweb:1567:13)
    at stackTrace (tanks.wasm.framework.unityweb:1584:12)
    at abort (tanks.wasm.framework.unityweb:16551:44)
    at abortOnCannotGrowMemory (tanks.wasm.framework.unityweb:1630:3)
    at enlargeMemory (tanks.wasm.framework.unityweb:1635:3)
    at wasm-function[33580]:70
    at wasm-function[33468]:3968
    at wasm-function[2583]:3
    at wasm-function[6537]:3
    at wasm-function[6528]:13
    at wasm-function[2694]:694
    at wasm-function[2699]:35
    at wasm-function[2687]:95
    at wasm-function[4981]:128
    at wasm-function[4400]:7
    at wasm-function[4688]:299
    at wasm-function[4683]:550
    at wasm-function[4476]:195
    at wasm-function[3465]:376
    at wasm-function[3436]:1422
    at wasm-function[3429]:63
    at wasm-function[33750]:12
    at dynCall_v [Object.UnityLoader.7a204835ae937c2b3ab5cd9517cfc805.Module.dynCall_v] (tanks.wasm.framework.unityweb:16273:86)
    at browserIterationFunc (tanks.wasm.framework.unityweb:2612:30)
    at runIter [Object.runIter] (tanks.wasm.framework.unityweb:2728:13)
    at Browser_mainLoop_runner (tanks.wasm.framework.unityweb:2667:26)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by hun-nemethpeter** [comment] 2017-12-30 03:21
Wow, I found a workaround. Open the tank demo page at [http://webassembly.org/demo/](http://webassembly.org/demo/)

1. Click "Play WebAssembly" button
2. When you see the "Made with Unity" then immediately click to an other tab page
3. Wait some second
4. Switch back to the tank demo page and voila

I can reproduce this bug 100%

**Comment by titzer** [comment] 2018-01-08 14:48
The root cause of this is the inability to get more memory for the grow memory operation in the browser.  Recommend:

1. Fix tanks demo to no longer rely on grow memory, by preallocating memory. It is very likely that the maximum memory needed by the demo isn't very much, and memory exhaustion is due to the need to keep both the old memory and the new memory during the copying process.

2. File a Chromium bug and we will investigate the issue.

**Comment by adanilo** [comment] 2018-06-21 01:49
Verified as working in Chrome and Firefox and Safari today. Closing, feel free to re-open if this happens again.

**Comment by xia-mu** [comment] 2018-06-24 01:21
I get this browser alert upon loading the Tanks demo:
```Out of memory. If you are the developer of this content, try allocating more memory to your WebGL build in the WebGL player settings```
OS: Windows 10
Browsers: 
Firefox 60.0.2
Chrome 67.0.3396.87

**Comment by steveklabnik** [comment] 2018-06-25 14:03
FWIW, I'm on Windows, FX 62 nightly, and it works just fine. Windows 10.

**Comment by steveklabnik** [comment] 2018-06-25 14:04
FWIW, I'm on Windows, FX 62 nightly, and it works just fine. Windows 10.

**Comment by Borthralla** [comment] 2019-01-27 17:17
I had this problem just now using Chrome on Windows 10. Was able to do the work around where you switch tabs which fixed the problem.

**Comment by Naphier** [comment] 2019-05-13 02:04
Issue persists on Chrome (Version 74.0.3729.131 (Official Build) (64-bit)) and Firefox (66.0.3 (64-bit)) on Windows 10 (1809). Edge works...

```
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 50331648, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (tanks.wasm.framework.unityweb:1567:13)
```

[webassembly.org-1557712689626.log.txt](https://github.com/WebAssembly/website/files/3170872/webassembly.org-1557712689626.log.txt)

Makes me not want to look further into WebAssembly. Seems it's not ready for prime time if even the demo doesn't work (I know this is a common Unity web build issue, maybe demo with something else?).

**Comment by binji** [comment] 2019-05-22 00:14
Closing since the demo is now removed.

**Closed by binji** 2019-05-22 00:14 UTC
