### ISSUE TITLE
Useless demo - Out of memory - when only 50% of ram is used

### ISSUE THREAD

**Issue by adaptabi** [WebAssembly/website#110] opened 2018-01-05 10:36 UTC
Only 50% of RAM is used on am Macbook Pro mid 2015 on windows 10/bootcamp but the strange error occurs `out of memory`
![image](https://user-images.githubusercontent.com/485535/34605644-a45b3b14-f20c-11e7-80af-6a5093355cd5.png)

**Comment by xtuc** [comment] 2018-01-05 11:46
The amount of memory available on your machine and available in WebAssembly/Browser are two separated things.

Duplicate of https://github.com/WebAssembly/website/issues/87

> Useless demo

That doesn't mean the demo is useless...

**Comment by adaptabi** [comment] 2018-01-05 12:05
Useless in the sense it doesn't work - so you cannot play / take webassembly for a spin.

**Comment by binji** [comment] 2019-05-22 00:13
Closing since the demo is now removed.

**Closed by binji** 2019-05-22 00:13 UTC
